import './css/main.css';
import { initialRender } from './page';
import { initialTasks } from './log';

initialRender.renderLogo();
initialRender.renderPlus();
initialRender.renderDueDates('Today');
initialRender.renderDueDates('Upcoming');
initialRender.renderDueDates('Someday');
initialRender.renderProjectSections('Family');
initialRender.renderProject('Vacation in Rome');
initialRender.renderProjectSections('Work');
initialRender.renderProject('Prepare Presentation');
initialRender.renderProjectSections('Hobbies');
initialRender.renderProject('Learn Basic Italian');
initialRender.renderAddList();
initialRender.renderMainTitle();
initialRender.renderMainContainer();
// initialRender.renderMainSub(document.querySelector('#cardBox'));
initialTasks.addTask('Receive Funds', 'Need Money', 'August', 1);
initialTasks.addTask('Open Account', 'Need Money', 'August', 1);
initialTasks.addTask('Spend Money', 'Need Money', 'August', 1);
initialTasks.renderTasks();