import './css/main.css';
import { initialRender } from './page';
import { initialTasks } from './log';
import star from './star.svg';
import calendar from './calendar-month.svg';
import archive from './archive.svg';

initialRender.renderLogo();
initialRender.renderPlus();
initialRender.renderDueDates('Today', star, 'star');
initialRender.renderDueDates('Upcoming', calendar, 'calendar');
initialRender.renderDueDates('Someday', archive, 'archive');
initialRender.renderProjectSections('Family');
initialRender.renderProject('Vacation in Rome');
initialRender.renderProjectSections('Work');
initialRender.renderProject('Prepare Presentation');
initialRender.renderProjectSections('Hobbies');
initialRender.renderProject('Learn Basic Italian');
initialRender.renderAddList();
initialRender.renderMainTitle();
initialRender.renderMainContainer();
// initialRender.renderMainSub(document.querySelector('#cardBox'));
initialTasks.addTask('Receive Funds', 'Need Money', 'August', 1);
initialTasks.addTask('Open Account', 'Need Money', 'August', 1);
initialTasks.addTask('Spend Money', 'Need Money', 'August', 1);
initialTasks.renderTasks();